//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTy.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONGVIEC()
        {
            this.NHIEMVUs = new HashSet<NHIEMVU>();
            this.CONGVIEC1 = new HashSet<CONGVIEC>();
        }
    
        public int MaCV { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> CVTienQuyet { get; set; }
        public string TenCV { get; set; }
        public Nullable<float> TienDo { get; set; }
        public string TenNhom { get; set; }
        public Nullable<int> MaDA { get; set; }
        public string MaGiaiDoan { get; set; }
    
        public virtual GIAIDOAN GIAIDOAN { get; set; }
        public virtual TRUONGNHOM TRUONGNHOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHIEMVU> NHIEMVUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGVIEC> CONGVIEC1 { get; set; }
        public virtual CONGVIEC CONGVIEC2 { get; set; }
    }
}
