//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTy.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUAN()
        {
            this.GIAIDOANs = new HashSet<GIAIDOAN>();
            this.TRUONGNHOMs = new HashSet<TRUONGNHOM>();
            this.TAINGUYENs = new HashSet<TAINGUYEN>();
        }
    
        public int MaDA { get; set; }
        public string TenDA { get; set; }
        public Nullable<float> TienDo { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public string ChiPhi { get; set; }
        public string TrangThai { get; set; }
        public string MaPM { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAIDOAN> GIAIDOANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRUONGNHOM> TRUONGNHOMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAINGUYEN> TAINGUYENs { get; set; }
    }
}
