//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTy.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.DIEMDANHs = new HashSet<DIEMDANH>();
            this.DUANs = new HashSet<DUAN>();
            this.NHIEMVUs = new HashSet<NHIEMVU>();
            this.NHOMs = new HashSet<NHOM>();
            this.TRUONGNHOMs = new HashSet<TRUONGNHOM>();
        }

        public NHANVIEN(string maNV, string hovaTenDem, string ten, string chucVu, string email, string levels, string diaChi, string sDT, string maTaiKhoan, string matKhau)
        {
            MaNV = maNV;
            HovaTenDem = hovaTenDem;
            Ten = ten;
            ChucVu = chucVu;
            Email = email;
            Levels = levels;
            DiaChi = diaChi;
            SDT = sDT;
            MaTaiKhoan = maTaiKhoan;
            MatKhau = matKhau;
        }

        public string MaNV { get; set; }
        public string HovaTenDem { get; set; }
        public string Ten { get; set; }
        public string ChucVu { get; set; }
        public string Email { get; set; }
        public string Levels { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string MaTaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEMDANH> DIEMDANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUAN> DUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHIEMVU> NHIEMVUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHOM> NHOMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRUONGNHOM> TRUONGNHOMs { get; set; }
    }
}
