//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTy.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHIEMVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHIEMVU()
        {
            this.NHIEMVU1 = new HashSet<NHIEMVU>();
        }
    
        public string MaNhiemVu { get; set; }
        public string MaTienQuyet { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> ThoiGianLamThucTe { get; set; }
        public string TenNhiemVu { get; set; }
        public Nullable<int> ThoiGianUocTinh { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> MaCV { get; set; }
    
        public virtual CONGVIEC CONGVIEC { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHIEMVU> NHIEMVU1 { get; set; }
        public virtual NHIEMVU NHIEMVU2 { get; set; }
    }
}
