//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTy.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOCLUONG
    {
        public string MaNV { get; set; }
        public int MaDA { get; set; }
        public string MaGiaiDoan { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public Nullable<int> TimeSprint { get; set; }
        public Nullable<int> TimeTasks { get; set; }
    }
}
