//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTy.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DanhSachNhiemVuNhom
    {
        public string MaNV { get; set; }
        public Nullable<int> MaDA { get; set; }
        public string MaGiaiDoan { get; set; }
        public int MaCV { get; set; }
        public string TenNhom { get; set; }
        public string MaNhiemVu { get; set; }
        public string TenNhiemVu { get; set; }
        public string TrangThai { get; set; }
        public string MaTienQuyet { get; set; }
        public Nullable<int> ThoiGianUocTinh { get; set; }
        public Nullable<int> ThoiGianLamThucTe { get; set; }
    }
}
